import { Inter } from "next/font/google"
import { cn } from "../../app/../lib/utils"
import  Sidebar  from "./Sidebar"
import NextBreadcrumb from '@/components/NextBreadcrumb'
import { FaChevronRight } from "react-icons/fa";
import { Toaster } from "@/components/ui/toaster"
import Navbar from "./Navbar";
const inter = Inter({ subsets: ["latin"] })
export const metadata = {
  title: "Background-Verification-Portal ",
  description: "Generated by create next app"
}
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body
        className={cn(
          "min-h-screen w-full bg-white text-black flex ",
          inter.className,
          {
            "debug-screens": process.env.NODE_ENV === "development"
          }
        )}
      >
        <div className="flex w-full">
        <Sidebar />
       
        <Toaster  className="custom-notification"/>
        <div className="pb-8 w-full relative ">
          <Navbar/>
        <div className="px-8">
        <NextBreadcrumb
          activeClasses='text-amber-500'
          containerClasses='sm:flex grid py-5 mt-0 items-center' 
          listClasses='hover:underline gap-2 font-bold md:text-base text-sm md:font-semibold font-medium'
          capitalizeLinks
          separator={<span className="mx-2"> <FaChevronRight style={{width:"8px"}} className="sm:rotate-0 rotate-90"/> </span>}
        />
        {children}</div></div>
        </div>
      </body>
    </html>
  )
}
